# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0
[package]
name = "idl2rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
dust_dds_gen = "0.11.0"
