# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0
[package]
name = "ppr"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap ={ version = "4.5.23", features = ["derive"]}
