[package]
name = "rocksdb-inspector"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "0.24.0"
tokio = { version = "1.43.1", features = ["full"] }
serde_json = "1.0.143"
clap = { version = "4.5.47", features = ["derive"] }