# SPDX-License-Identifier: Apache-2.0

yaml_storage: /etc/piccolo/yaml
piccolo_cloud: http://127.0.0.1:41234
host:
  name: HPC
  ip: 127.0.0.1
  type: vehicle
  role: master
dds:
  idl_path: src/vehicle/dds/idl
  domain_id: 100
  # Removed out_dir - will use Cargo's default OUT_DIR
