# SPDX-License-Identifier: Apache-2.0

yaml_storage: /root/piccolo_yaml
doc_registry: http://0.0.0.0:41234
host:
  name: HPC
  ip: 0.0.0.0
guest:
  - name: ZONE
    ip: 192.168.10.68
    ssh_port: 22
    id: root
    pw: lge123
