# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0
accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "0BSD",
    "Unicode-3.0",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
]
