# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "2"

members = [
    "ppr",
    "idl2rs",
    "yamlvalidator",
    "rocksdb-inspector",
    "settingscli"
]

[workspace.dependencies]
common = { path = "../common" }
